# Generated by Django 3.1.7 on 2021-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_cost',
            field=models.CharField(default=30, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_duration',
            field=models.CharField(default=30, max_length=200),
            preserve_default=False,
        ),
    ]
